version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+asyncmy://app_user:app_password@db:3306/app_db"
    ports:
      - "8000:8000"
    command: >
      sh -c "
          ./wait-for-it.sh db:3306 --timeout=60 --strict -- \
          alembic upgrade head &&
          ( [ -f /app/.imported ] || (python import_db.py && touch /app/.imported) ) &&
          uvicorn main:app --host 0.0.0.0 --port 8000
        "
    volumes:
      - .:/app

volumes:
  db_data: