"""Fixed actual return date in Credit. Nullable now

Revision ID: 392503a4a859
Revises: 028739c3c951
Create Date: 2025-09-13 15:58:32.366772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392503a4a859'
down_revision: Union[str, Sequence[str], None] = '028739c3c951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'actual_return_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'actual_return_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
