"""Fixed numeric fields

Revision ID: 5e540ce32bfc
Revises: df454657122f
Create Date: 2025-09-13 21:14:39.502004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e540ce32bfc'
down_revision: Union[str, Sequence[str], None] = 'df454657122f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'body',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'sum',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('plans', 'sum',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'sum',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'sum',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('credits', 'body',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
