"""Fixed field percent for credit

Revision ID: df454657122f
Revises: 5aef1435dadd
Create Date: 2025-09-13 20:41:59.168237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df454657122f'
down_revision: Union[str, Sequence[str], None] = '5aef1435dadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'body',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('credits', 'percent',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'sum',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('plans', 'sum',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'sum',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'sum',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('credits', 'percent',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=3, scale=2),
               existing_nullable=False)
    op.alter_column('credits', 'body',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
