"""Created all models

Revision ID: e9c521aa8007
Revises: 0baa39472158
Create Date: 2025-09-13 01:28:25.400743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c521aa8007'
down_revision: Union[str, Sequence[str], None] = '0baa39472158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issuance_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('plans')
    op.drop_table('credits')
    op.drop_table('users')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
